DECLARE @ColumnName nvarchar(128) = N'MaDangKy%'
SELECT TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE @ColumnName
  AND TABLE_NAME IN (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE')
ORDER BY TABLE_NAME, COLUMN_NAME;